import type {
  SalonStats,
  CustomerSegmentStat,
  Campaign,
  Customer,
  SalonReply,
  MessageFunnelStep,
} from '../types/crm';

export const mockSalonOwner = {
  name: 'Elena Vance',
  role: 'Salon Director & Lead Stylist',
  salonName: 'LUMIÈRE Studio',
  salonTagline: 'Luxury Hair & Wellness Sanctuary',
  email: 'elena@lumierestudio.com',
  phone: '+1 (555) 439-8820',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
};

export const mockStats: SalonStats = {
  totalCustomers: 850,
  activeCustomers: 812,
  messagesSent: 720,
  delivered: 695,
  read: 540,
  replies: 47,
  blockedOptOut: 38,
  lastCampaignName: 'Weekend Glow & Balayage Special',
  lastCampaignDeliveryRate: 98,
};

export const mockCustomerSegments: CustomerSegmentStat[] = [
  {
    segment: 'Regular',
    label: 'Regular Clients',
    count: 510,
    percentage: 60,
    color: '#0284C7',
    description: 'Clients visiting every 4-6 weeks for regular cuts & color treatments',
  },
  {
    segment: 'VIP',
    label: 'VIP Circle',
    count: 142,
    percentage: 17,
    color: '#E85D75',
    description: 'Top spenders with priority bookings and premium styling packages',
  },
  {
    segment: 'New',
    label: 'New Clients',
    count: 118,
    percentage: 14,
    color: '#16A34A',
    description: 'First-time visitors joined within the last 45 days',
  },
  {
    segment: 'Inactive',
    label: 'Inactive',
    count: 42,
    percentage: 5,
    color: '#D97706',
    description: 'Clients with no appointments in the past 90 days',
  },
  {
    segment: 'OptedOut',
    label: 'Opted-out / Blocked',
    count: 38,
    percentage: 4,
    color: '#94A3B8',
    description: 'Unsubscribed from automated WhatsApp campaigns',
  },
];

export const mockMessageFunnel: MessageFunnelStep[] = [
  {
    label: 'Messages Sent',
    count: 720,
    rate: '100%',
    percentage: 100,
    color: '#7C3AED',
  },
  {
    label: 'Delivered',
    count: 695,
    rate: '96.5%',
    percentage: 96.5,
    color: '#0284C7',
  },
  {
    label: 'Read',
    count: 540,
    rate: '77.6%',
    percentage: 77.6,
    color: '#D97706',
  },
  {
    label: 'Client Replies',
    count: 47,
    rate: '8.7%',
    percentage: 8.7,
    color: '#059669',
  },
];

export const mockRecentCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Weekend Glow & Balayage Special',
    type: 'Promotional Offer',
    sentAt: 'Today at 09:30 AM',
    audience: 'VIP & Regular (410)',
    totalRecipients: 410,
    deliveredCount: 402,
    readRatePercent: 82,
    repliesCount: 29,
    status: 'Sent',
  },
  {
    id: 'camp-2',
    name: 'Autumn Keratin Care Reminder',
    type: 'Automated Care',
    sentAt: 'Yesterday at 02:15 PM',
    audience: 'Keratin Clients (185)',
    totalRecipients: 185,
    deliveredCount: 180,
    readRatePercent: 74,
    repliesCount: 12,
    status: 'Sent',
  },
  {
    id: 'camp-3',
    name: 'We Miss You! 15% Off Your Next Refresh',
    type: 'Re-engagement',
    sentAt: 'Oct 18 at 11:00 AM',
    audience: 'Inactive > 60d (125)',
    totalRecipients: 125,
    deliveredCount: 113,
    readRatePercent: 61,
    repliesCount: 6,
    status: 'Sent',
  },
  {
    id: 'camp-4',
    name: 'Exclusive VIP Holiday Pre-Booking',
    type: 'Exclusive Access',
    sentAt: 'Scheduled for Friday',
    audience: 'VIP Tier Only (142)',
    totalRecipients: 142,
    deliveredCount: 0,
    readRatePercent: 0,
    repliesCount: 0,
    status: 'Scheduled',
  },
];

export const mockRecentCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Sophia Laurent',
    phone: '+1 (555) 234-5678',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    segment: 'VIP',
    lastVisit: 'Today, 11:30 AM',
    totalSpent: 1420,
    totalVisits: 14,
    tags: ['Balayage', 'Olaplex', 'Gloss'],
    status: 'active',
  },
  {
    id: 'cust-2',
    name: 'Camilla Dupont',
    phone: '+1 (555) 876-5432',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    segment: 'Regular',
    lastVisit: 'Yesterday, 4:00 PM',
    totalSpent: 680,
    totalVisits: 6,
    tags: ['Roots', 'HydraFacial'],
    status: 'active',
  },
  {
    id: 'cust-3',
    name: 'Isabella Moreno',
    phone: '+1 (555) 345-6789',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150',
    segment: 'New',
    lastVisit: '2 days ago',
    totalSpent: 210,
    totalVisits: 1,
    tags: ['First Visit', 'Signature Cut'],
    status: 'active',
  },
  {
    id: 'cust-4',
    name: 'Genevieve Ross',
    phone: '+1 (555) 901-2345',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=150',
    segment: 'Regular',
    lastVisit: '3 days ago',
    totalSpent: 940,
    totalVisits: 9,
    tags: ['Highlights', 'Blowout'],
    status: 'active',
  },
  {
    id: 'cust-5',
    name: 'Charlotte Sterling',
    phone: '+1 (555) 678-1234',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=150',
    segment: 'VIP',
    lastVisit: 'Oct 19',
    totalSpent: 2150,
    totalVisits: 22,
    tags: ['Hair Spa', 'Full Foil', 'Extension Care'],
    status: 'active',
  },
];

export const mockRecentReplies: SalonReply[] = [
  {
    id: 'rep-1',
    customerId: 'cust-1',
    customerName: 'Sophia Laurent',
    customerPhone: '+1 (555) 234-5678',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    messagePreview: 'Hi Elena! Loved the balayage offer. Can I add a deep conditioning treatment too?',
    timestamp: '12m ago',
    unread: true,
    relatedCampaign: 'Weekend Glow & Balayage Special',
  },
  {
    id: 'rep-2',
    customerId: 'cust-2',
    customerName: 'Camilla Dupont',
    customerPhone: '+1 (555) 876-5432',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    messagePreview: 'Thank you for the keratin maintenance guide! My hair feels fantastic.',
    timestamp: '45m ago',
    unread: true,
    relatedCampaign: 'Autumn Keratin Care Reminder',
  },
  {
    id: 'rep-3',
    customerId: 'cust-6',
    customerName: 'Nathalie Chen',
    customerPhone: '+1 (555) 789-0123',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=150',
    messagePreview: 'Is Elena available this Saturday around 3 PM for toner refresh?',
    timestamp: '2h ago',
    unread: false,
    relatedCampaign: 'Weekend Glow & Balayage Special',
  },
  {
    id: 'rep-4',
    customerId: 'cust-7',
    customerName: 'Maya Patel',
    customerPhone: '+1 (555) 456-7890',
    avatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=150',
    messagePreview: 'Please reserve a slot for me and my sister!',
    timestamp: '4h ago',
    unread: false,
  },
];
